config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'search/create'

  devise_for :users
  resources :payment_types
  resources :clients do
  resources :payments, only:[ :new, :create, :edit, :update, :destroy, :show]
end
  resources :payments, only:[:index]

  root "welcome#index"
  put "clients/:id/Inactivado" , to: "clients#Inactivado"
  put "clients/:id/Activar" , to: "clients#Activar"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  include AASM
  has_many :payments
  has_many :payment_types, :through => :payments

  validates :nombre, presence: true
  validates :apellido, presence: true
  validates :cedula, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :telefono, presence: true, numericality: true
  validates :nacimiento, presence: true
  validates :direccion, presence: true

  has_attached_file :foto,:styles => {
      :thumb => "100x100#",
      :small  => "150x150>",
      :medium => "300x300" }
  validates_attachment_content_type :foto, content_type: /\Aimage\/.*\z/

  aasm column: "state" do
    state :Activo
    state :Inactivo

    event :Activado do
      transitions from: :Inactivo, to: :Activo
    end

    event :Inactivado do
      transitions from: :Activo, to: :Inactivo
    end

  end
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :client
  belongs_to :payment_type
  #scope :ultimos, -> { ("DISTINCT ON (client_id) * ").order("client_id, fecha_payment ASC") }
  #ultimos sqlite group(client_id).order("fecha_payment ASC")
  scope :ultimos, -> { group(:client_id).order("fecha_payment ASC") }
  after_create :update_monto
  #after_create :send_mails

#def send_mails
#  ClientMailer.new_payment(self).deliver_later
#end

  def update_monto
     payment = Payment.last.payment_type_id
     monto = PaymentType.find_by(id: payment)
     monto2= monto.monto_type
    self.update_column(:monto_payment, monto2)
  end
end

app/models/payment_type.rb
class PaymentType < ApplicationRecord
  has_many :payments
  has_many :clients, :through => :payments
  def descripcion_monto
   "#{descripcion_type}. #{monto_type}"
 end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :authenticate_user!

  def index
  @clients =  Client.all.page(params[:page]).per(8)
  end

  def show
  @Clients = Client.find(params[:id])
  @payments = Payment.new
  @type = PaymentType.all
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)
    respond_to do |format|
            if @client.save
              format.html { redirect_to @client, notice: 'Cliente añadido correctamente.' }
              format.json { render :show, status: :created, location: @client }
            else
              format.html { render :new }
              format.json { render json: @client.errors, status: :unprocessable_entity }
            end
        end
    end

  def destroy
      @Client = Client.find(params[:id])
      @Client.destroy
      redirect_to clients_path
  end


  def edit
    @client = Client.find(params[:id])
  end

  def update
    @client = Client.find(params[:id])
    if @client.update(client_params)
     redirect_to @client
   else
     render :edit
   end
  end


  def Inactivado
  @client = Client.find(params[:id])
  @client.Inactivado!
  redirect_to @client
  end

  def Activar
  @client = Client.find(params[:id])
  @client.Activado!
  redirect_to @client
  end

  private

  def client_params
        params.require(:client).permit(:nombre, :apellido, :cedula, :foto, :email, :telefono, :direccion, :nacimiento)
  end

end

app/controllers/payment_types_controller.rb
class PaymentTypesController < ApplicationController
  before_action :authenticate_user!


  def index
    @type = PaymentType.all
  end
  def new
    @types = PaymentType.new
  end
  def create
    @types = PaymentType.new(payment_types_params)

    respond_to do |format|
          if @types.save
            format.html { redirect_to payment_types_path, notice: 'El tipo de pago was successfully created.' }
            format.json { render :show, status: :created, location: @types }
            format.json { render :show, status: :created, location: @types }
          else
            format.html { render :new }
            format.json { render json: @types.errors, status: :unprocessable_entity }
          end
        end
end

def show
  @types = PaymentType.find(params[:id])
end
def edit
  @types = PaymentType.find(params[:id])
end

def update
  @types = PaymentType.find(params[:id])
  if @types.update(payment_types_params)
   redirect_to payment_types_path
 else
   render :edit
end
end
  private
    def payment_types_params
        params.require(:payment_type).permit(:descripcion_type, :monto_type)
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_payment, except: [:index,:new, :create]
  before_action :set_client, except:[:index]

 def index
   #@payment = Payment.ultimos
   @payment = Payment.select("DISTINCT ON (client_id) * ").order("client_id, fecha_payment DESC")
   @timenow = Date.today - 1.month
   @timenow1 = Date.today
 end
 def show
 end
  def new
    @payments = Payment.new
    @type = PaymentType.all

  end
  def create
    @payments = Payment.new(payment_params)
    @payments.client = @client
    respond_to do |format|
          if @payments.save
            format.html { redirect_to @payments.client, notice: 'El pago ha sido creado correctamente.' }
            format.json { render :show, status: :created, location: @payments.client }
            format.js
          else
            format.html { render :new }
            format.json { render json: @payments.errors, status: :unprocessable_entity }
          end
        end
end

def destroy
end
  private
def set_client
@client = Client.find(params[:client_id])
end
def set_payment
@payment = Payment.find(params[:id])
end
  def payment_params
        params.require(:payment).permit(:fecha_payment,:client_id,:payment_type_id)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def create
  cedula = params[:search]
  @clients = Client.where("cedula = ? OR nombre LIKE ?", cedula, cedula)
  respond_to do |format|
    format.html {redirect_to root_path}
    format.json { render json: @clients }
    format.js
  end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!
  def index
     @payment = Payment.select("DISTINCT ON (client_id) * ").order("client_id, fecha_payment DESC")
     # sqlite group(client_id).order("fecha_payment DESC")
     #@payment = Payment.group(:client_id).order("fecha_payment DESC")
     @timenow = Date.today - 1.month
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inscription_helper.rb
module InscriptionHelper
end

app/helpers/monthly_payment_helper.rb
module MonthlyPaymentHelper
end

app/helpers/payment_helper.rb
module PaymentHelper
end

app/helpers/payment_types_helper.rb
module PaymentTypesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/clients/_client.html.erb
<div class="col-sm-4 col-md-3 col-xs-12">
  <div class="thumbnail">
    <%= image_tag client.foto.url%>
    <div class="caption">
    <p class="text-capitalize Ncliente">  <%= client.nombre %> <%= client.apellido%> </p>
    <p class="Dcliente"> Cédula: <%= client.cedula %></p>
    <p class="Dcliente"> Estado del cliente: <%= client.state %></p>
    <button type="button" class="btn btn-info"><%= link_to "Ver perfil", client %></button>
      </div>
    </div>
</div>

app/views/clients/_form.html.erb
<div class="nuevo">
    <%= form_for (@client) do |f| %>
    <% @client.errors.full_messages.each do |message| %>
    <div class="alert alert-danger">
        <%= message %>
    </div>
  <% end %>
  <div class="col-sm-12 col-md-12 col-xs-12">
    <%= f.file_field :foto, class: " anchura" %>
  </div>
  <div class="col-sm-12 col-md-12 col-xs-12">
    <%= f.text_field :nombre, placeholder: "Nombre", class: "form-control anchura" %>
  </div>
  <div class="col-sm-12 col-md-12 col-xs-12">
    <%= f.text_field :apellido, placeholder: "Apellido", class: "form-control anchura" %>
  </div>
  <div class="col-sm-12 col-md-12 col-xs-12">
    <%= f.text_field :cedula, placeholder: "Cedula", class: "form-control anchura" %>
  </div>
  <div class="col-sm-12 col-md-12 col-xs-12">
    <%= f.email_field :email, placeholder: "Email", class: "form-control anchura" %>
  </div>
  <div class="col-sm-12 col-md-12 col-xs-12">
    <%= f.telephone_field :telefono, placeholder: "Telefono", class: "form-control anchura" %>
  </div>
  <div class="col-sm-4 col-md-3 col-xs-4">
    <%= f.label :Fecha_de_nacimiento, class: "label-control margin-top"%>
  </div>
  <div class="col-sm-4 col-md-9 col-xs-8 ">
    <%= f.date_field :nacimiento , class: "form-control anchura"%>
  </div>
  <div class="col-sm-12 col-md-12 col-xs-12">
    <%= f.text_field :direccion, placeholder: "Direccion", class: "form-control anchura" %>
  </div>
  <div class="col-sm-12 col-md-12 col-xs-12">
    <%= f.submit "Guardar",class: "btn btn-success" %>
  </div>
<% end %>
</div>

app/views/clients/edit.html.erb
<div class="container ">
<h1 class="text-center">Editar cliente</h1>
<div class="row nuevosc">
<%= render "form" %>
</div>
</div>

app/views/clients/index.html.erb
<div class="container-fluid">
<div class="container-fluid">
<div  class="row", id="resultados">


</div>
</div>
</div>

<div class="container-fluid">
  <div class="row">
    <div class="col-sm-12 col-md-12 col-xs-12 anchura">
      <div class="container-fluid">

        <%= form_tag "/search/create", method: :get, remote: true, id: "search_f" do %>
          <%= text_field_tag(:search,params[:search],placeholder: "Buscador de clientes", class: "form-control form-control-1"  ) %>
            <%= content_tag :button, type: :submit, class: "btn btn-default" do %>
              Buscar
            <% end %>
          </div>
    </div>
    </div>
    <% end %>



<div class="container-fluid">
    <div class="row">
    <%= render @clients %>
  </div>
  <nav aria-label="...">
    <ul class="pager">
    <li> <%= link_to_prev_page @clients, 'Anterior' %></li>
    <li> <%= link_to_next_page @clients, 'Siguiente' %></li>
  </ul>
</nav>
</div>

app/views/clients/new.html.erb
<div class="container">
<div class="row nuevosc">
<%= render "form" %>
</div>
</div>

app/views/clients/show.html.erb
<div class="container-fluid">
  <div class="row">


    <div class="col-sm-6 col-md-3 col-xs-12">
      <div class="thumbnail">
        <%= image_tag @Clients.foto.url %>
        <h1><%= @Clients.nombre %>  <%= @Clients.apellido %> </h1>
        <p> Cedula: <%= @Clients.cedula %></p>
        <p> Email: <%= @Clients.email %></p>
        <p> Telefono: <%= @Clients.telefono %></p>
        <p> Direccion: <%= @Clients.direccion %></p>
        <p> Fecha de nacimiento: <%= @Clients.nacimiento %></p>
        <button type="button" class="btn btn-warning">  <%= link_to "Editar", edit_client_path() %></button>
        <% if @Clients.may_Inactivado? %>
        <button type="button" class="btn btn-danger"><%= link_to "Inactivar", "/clients/#{@Clients.id}/Inactivado", method: :put, data: { confirm: '¿Estás seguro?' } %></button>
        <% else %>
        <button type="button" class="btn btn-danger"><%= link_to "Activar", "/clients/#{@Clients.id}/Activar", method: :put, data: { confirm: '¿Estás seguro?' } %></button>
        <% end %>
      </div>
    </div>


    <div class="col-sm-6 col-md-3 col-xs-12">
        <div class="cuadrito">
          <div class="container-fluid">
              <%= render "payments/form" %>
          </div>
          </div>
    </div>

    <div class="col-sm-12 col-md-6 col-xs-12">
        <div class="cuadrito">
                  <p class="text-center titulo Ncliente">Historial de pagos</p>
                    <div class="center-box padding">
                      <div class="table-responsive">
                        <table class="table  table-hover ">
                          <thead>
                            <tr>
                              <th>Tipo de pago</th>
                              <th>Monto</th>
                              <th>Fecha</th>
                            </tr>
                          </thead>

                          <tbody>
                          <% @Clients.payments.order("fecha_payment DESC").each do |payment| %>
                              <tr>
                                <td><p class="detalles-cliente"><%= payment.payment_type.descripcion_type %></p>
                                </td>
                                <td><p class="detalles-cliente"><%= payment.monto_payment %></p>
                                </td>
                                <td>
                                  <p class="detalles-cliente"> <%=  payment.fecha_payment.strftime("%d-%m-%Y") %></p>
                                </td>
                              </tr>
                              <% end %>
                          </tbody>
                        </table>
                      </div>
                    </div>
      </div>
    </div>
   </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gym</title>
    <%= csrf_meta_tags %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>
  <body>
    <% if user_signed_in? %>
    <%= render "/parciales/navegacion" %>
    <% end %>
    <div class="container">
      <div class="alert alert-success ", style="<%= "display: none;" if notice.nil? %>">
        <p class="notice"> <%= notice %></p>
      </div>
      <div class="alert alert-danger ", style="<%= "display: none;" if alert.nil? %>">
        <p class="alert"> <%= alert %></p>
      </div>
    </div>
    <%= yield %>

    <footer class="footer ">
      <div class="container text-center position">
          <p class="text-muted"><a href="https://www.instagram.com/carlosluishc/" title="Contactate conmigo"> By Carlos Hernández</a>,todos los derechos reservados </p>
        </div>
    </footer>
  </body>
</html>

app/views/parciales/_navegacion.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#Mynav" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="Mynav">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to "Inicio", root_path %>
        </li>
        <li>
          <%= link_to "Nuevos Clientes", new_client_path %>
        <li>
        <%= link_to "Clientes", clients_path %>
        </li>
        <li>
        <%= link_to "Deudores", payments_path %>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Tipos de pago<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Todos", payment_types_path %></li>
            <li><%= link_to "Nuevo", new_payment_type_path %></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <%= current_user.email %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
          <% if user_signed_in? %>
              <li class="">
                <%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete %>
                <%= link_to "Admin panel", rails_admin_path %>
              </li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/payment_types/_form.html.erb
<%= form_for ([@types]) do |f| %>
<% @types.errors.full_messages.each do |message| %>
<div class=" alert alert-danger">
  <%= message %>
<% end %>
  </div>
<div class="row nuevosp">
    <div class="col-sm-12 col-md-12 col-xs-12">
    <%= f.text_field :descripcion_type, placeholder: "Descripción", class: "form-control anchura" %>
  </div>
  <div class="col-sm-12 col-md-12 col-xs-12">
    <%= f.text_field :monto_type, placeholder: "Monto" , class: "form-control anchura"%>
  </div>
  <div class="col-sm-12 col-md-12 col-xs-12">
    <%= f.submit "Guardar", class: "btn btn-success" %>
  </div>
</div>

<% end %>

app/views/payment_types/edit.html.erb
<div class="container-fluid">
<%= render "form" %>
</div>

app/views/payment_types/index.html.erb
<div class="container-fluid">
<div class="container center-box">
<table class="table table-responsive table-hover">
  <thead>
    <tr>
      <th>Pagos Creados</th>
      <th>Monto</th>
    </tr>
  </thead>
  <tbody>
    <% @type.each do |type| %>
      <tr>
        <td><p class="nombre-cliente"><%= type.descripcion_type %></p>
        </td>
        <td><p class="detalles-cliente"><%= type.monto_type %></p>
        </td>
        <td><p class="detalles-cliente"><%= link_to "Editar", edit_payment_type_path(type) %></p>
        </td>
      <% end %>
  </tbody>
</table>
</div>
</div>

app/views/payment_types/new.html.erb
<div class="container-fluid">
<%= render "form" %>
</div>

app/views/payment_types/show.html.erb
<h1><%= @types.descripcion_type %> <%= @types.monto_type %></h1>

app/views/payments/_form.html.erb
  <%= form_for ([@Clients, @payments]) do |f| %>
  <% @payments.errors.full_messages.each do |message| %>
  <div class="alert alert-danger">
    <%= message %>
  </div>
  <% end %>

    <div class="row">
    <div class="anchoC">
    <div class="col-sm-12 col-md-12 col-xs-12 anchura">
      <%= collection_select(:payment,:payment_type_id,@type,:id,:descripcion_type, {prompt: "Seleccione un tipo de pago"},class: "form-control input-sm") %>
    </div>
        <div class="col-sm-4 col-md-4 col-xs-4 margin-top">
          <label>Fecha:</label>
        </div>
    <div class="col-sm-8 col-md-8 col-xs-8 padding_left">
      <%= f.date_field :fecha_payment, class:"form-control input-sm" %>
    </div>
    <div class="col-sm-12 col-md-12 col-xs-12">
      <%= f.submit "Guardar" , class:"btn btn-success centrar" %>
    </div>
    </div>
  </div>
<% end %>

app/views/payments/_payment.html.erb
      <p class="nombre-cliente"><%= payment.client.nombre %> <%= payment.client.apellido %></p>
      <p class="detalles-cliente"> Tipo de pago: <%= payment.payment_type.descripcion_type %></p>
      <p class="detalles-cliente"> Monto: <%= payment.monto_payment %> </p>
      <p class="detalles-cliente"> fecha: <%= payment.fecha_payment %></p>

app/views/payments/index.html.erb
				<div class="container center-box">
          <h1 class="text-center">Deudores</h1>
					<div class="table-responsive">
						<table class="table table-hover">
							<thead>
								<tr>
									<th>Cliente</th>
	                <th>Cédula</th>
									<th>Tipo de pago</th>
									<th>Monto</th>
	                <th>Fecha</th>
	                <th>Deuda</th>
								</tr>
							</thead>

							<tbody>
	              <% @payment.each_with_index  do |payment| %>
	              <% if payment.fecha_payment <= @timenow and payment.client.state == "Activo" %>
	                <tr>
	                  <td><p class="nombre-cliente"><%= link_to payment.client.nombre, payment.client %> <%= link_to payment.client.apellido, payment.client %></p>
	                  </td>
	                  <td><p class="detalles-cliente"><%= payment.client.cedula %></p>
	                  </td>
	                  <td>
	                    <p class="detalles-cliente"> <%= payment.payment_type.descripcion_type %></p>
	                  </td>
	                  <td>
	                    <p class="detalles-cliente"> <%= payment.monto_payment %> </p>
	                  </td>
	                  <td>
	                    <p class="detalles-cliente"> <%= payment.fecha_payment.strftime("%d-%m-%Y") %> </p>
	                  </td>
	                  <td>
	                    <p class="detalles-cliente"> <% deuda = @timenow1.month - payment.fecha_payment.month %> <% if deuda == 1 %>
	                      <%= deuda %> Mes
	                      <% else %>
	                      <%= deuda %> Meses
	                    <% end %></p>
	                  </td>
									</tr>
	                <% end %>
	                <% end %>
							</tbody>
						</table>

					</div>

				</div>

app/views/payments/new.html.erb
<h1>Pagos</h1>
<%= render "form" %>

app/views/payments/show.html.erb
<h1><%= @payment.client.nombre %> <%= @payment.client.apellido %></h1>
<p><%= @payment.monto_payment %> - <%= @payment.fecha_payment %>  </p>
<p><%= @payment.payment_type.monto_type %> - <%= @payment.payment_type.descripcion_type %>  <%= link_to "Eliminar", @payment , method: :delete %> </p>

app/views/search/create.html.erb
<h1>Search#create</h1>
<p>Find me in app/views/search/create.html.erb</p>

app/views/welcome/index.html.erb
<p class="text-center tituloI">Ultimos pagos</p>
				<div class="container center-box ">
					<div class="table-responsive">
						<table class="table  table-hover ">
							<thead>
								<tr>
									<th>Cliente</th>
	                <th>Cédula</th>
									<th>Tipo de pago</th>
									<th>Monto</th>
	                <th>Fecha</th>
								</tr>
							</thead>

							<tbody>
	              <% @payment.each do |payment| %>
									<% if payment.client.state == "Activo" %>
									<tr>
									 <td><p class="nombre-cliente"><%= payment.client.nombre %> <%= payment.client.apellido %></p>
									 </td>
									 <td><p class="detalles-cliente"><%= payment.client.cedula %></p>
									 </td>
									 <td>
										 <p class="detalles-cliente"> <%= payment.payment_type.descripcion_type %></p>
									 </td>
									 <td>
										 <p class="detalles-cliente"> <%= payment.monto_payment %> </p>
									 </td>
									 <td>
										 <p class="detalles-cliente"><%= payment.fecha_payment.strftime("%d-%m-%Y") %></p>
									 </td>
								 </tr>
									<% end %>
	                <% end %>
							</tbody>
						</table>

					</div>

				</div>